CREATE TABLE node01 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    temp NUMBER NOT NULL,
    hum NUMBER NOT NULL,
    recieved TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE node02 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    temp NUMBER NOT NULL,
    hum NUMBER NOT NULL,
    recieved TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE node03 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    temp NUMBER NOT NULL,
    hum NUMBER NOT NULL,
    recieved TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE node04 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    temp NUMBER NOT NULL,
    hum NUMBER NOT NULL,
    recieved TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);